# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c008a0b522ed8732032415f24e01106667181beb6630cf4f7ebcc59fddac523ad1156236478f7581e6b7d9a6ea94a6763336117ca7acef55418e536dd7873fb2

test:
  secret_key_base: 080daa9c47b09efcfc5f6d1a349f0acef9c94ceafe6ad891abeb31eeeaf5a73e7cd14de0f0d1a56e13f6acd95e4c40989fd10c3c0a095987e339a7bf49aadce0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
